name: Python application test with Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies 
      run: | 
        cd project00/
        make install 
    - name: Lint with Pylint
      run: | 
        cd project00/
        make lint
    - name: Test with Pytest 
      run: | 
        cd project00/
        make test 
    - name: Format code with Python black 
      run: | 
        cd project00/
        make format
